### PR TITLE
Fix improper cookie header 

### PR DESCRIPTION
**Pull request by abador**
While testing the client it wasn't possible to use the session cookie for whoami requests. The root problem seemed to be a wrong way of setting the cookie header for the api call.  It seems that there was no support for session cookie name or kookie host in the  config so I also added it.

### CODE REVIEW

**Comment by aeneasr** [comment]
Thank you! Unfortunately this code is auto-generated from https://github.com/ory/sdk and the definition source in in the project itself so here https://github.com/ory/kratos

Your changes will be overwritten the next time there's an update from the automation pipeline!

**Comment by harnash** [comment]
@aeneasr looking at Swagger 2.x spec and https://swagger.io/docs/specification/2-0/authentication/ it looks like it does not provide Cookie based authentiaction schemas, it is present in 3.x though https://swagger.io/docs/specification/authentication/cookie-authentication/.

Sadly https://github.com/go-swagger/go-swagger/issues/1122#issuecomment-575968499 indicates that go-swagger will not implement the newest spec. This may render API Client unusable in some cases.

**Comment by aeneasr** [comment]
In Kratos 0.6 we have implemented a new pipeline which allows us to upgrade to oas 3.0 and also introduces the ability to apply targeted patches, which should make this possible!

**Comment by abador** [comment]
I figured as much since some docs also have similar irregularities. Let me know when it's finished. I can prepare a patch, changes are pretty straight forward.

**Comment by aeneasr** [comment]
This was fixed in Kratos and should thus be fixed in the next release!

**Pull request closed without merging**
